import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — UnchainedAPI",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20">
      <p className="section-label mb-4">// Legal</p>
      <h1 className="text-3xl font-mono font-bold text-neutral-100 mb-2">
        Terms of Service<span className="text-terminal-500">.</span>
      </h1>
      <p className="text-xs font-mono text-surface-800 mb-12">Last updated: March 5, 2026</p>

      <div className="space-y-10 text-sm text-surface-900 leading-relaxed font-mono">
        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">1. Agreement</h2>
          <p>
            By accessing or using UnchainedAPI (&quot;Service&quot;), operated at llm.ai-vfx.com, you agree to
            be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service.
            The Service is operated by UnchainedAPI (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">2. Description of Service</h2>
          <p>
            UnchainedAPI provides access to large language models (LLMs) via an OpenAI-compatible API.
            Models run on serverless GPU infrastructure (RunPod). You interact with the Service through
            API keys, a web playground, and a dashboard for managing your account.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">3. Account &amp; API Keys</h2>
          <p>
            You must register an account to use the Service. You are responsible for maintaining the
            confidentiality of your credentials and API keys. API keys are shown once upon creation —
            we store only their SHA-256 hashes and cannot recover lost keys. You are responsible for all
            activity under your account and API keys.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">4. Billing &amp; Credits</h2>
          <p>
            The Service uses a prepaid credit system. You purchase credits via our payment processor
            (Paddle). Usage is billed by actual GPU compute time consumed plus a margin, not by token
            count. Credits are non-transferable. Unused credits remain in your account indefinitely unless
            your account is terminated for Terms violations.
          </p>
          <p className="mt-3">
            Optional &quot;Keep Warm&quot; mode keeps model workers active and bills continuously at the
            posted hourly rate. If your credit balance reaches zero, Keep Warm is automatically disabled.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">5. Acceptable Use</h2>
          <p>You agree NOT to use the Service to:</p>
          <ul className="list-none mt-3 space-y-2 text-surface-800">
            <li><span className="text-terminal-600 mr-2">&gt;</span>Generate content that exploits, harms, or endangers minors in any way</li>
            <li><span className="text-terminal-600 mr-2">&gt;</span>Conduct or facilitate illegal activities under applicable law</li>
            <li><span className="text-terminal-600 mr-2">&gt;</span>Distribute malware, engage in phishing, or attack third-party systems</li>
            <li><span className="text-terminal-600 mr-2">&gt;</span>Resell or redistribute API access without authorization</li>
            <li><span className="text-terminal-600 mr-2">&gt;</span>Attempt to reverse-engineer, extract model weights, or circumvent rate limits</li>
            <li><span className="text-terminal-600 mr-2">&gt;</span>Abuse the Service in a way that degrades performance for other users</li>
          </ul>
          <p className="mt-3">
            We reserve the right to suspend or terminate accounts that violate these terms without prior
            notice and without refund.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">6. Model Content &amp; Disclaimer</h2>
          <p>
            The models available on UnchainedAPI include &quot;uncensored&quot; and &quot;abliterated&quot;
            variants that have reduced content filtering. Model outputs are generated by third-party open-source
            models, not by us. We do not endorse, verify, or guarantee the accuracy, safety, or legality of
            model outputs. You are solely responsible for how you use generated content.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">7. Availability &amp; Warranties</h2>
          <p>
            The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties of any
            kind, express or implied. We do not guarantee uninterrupted or error-free operation. Serverless
            infrastructure may experience cold starts, queue delays, or temporary unavailability. We are
            not liable for any losses resulting from downtime or service interruptions.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, UnchainedAPI and its operators shall not be liable for
            any indirect, incidental, special, consequential, or punitive damages, including loss of profits,
            data, or business opportunities, arising from your use of the Service. Our total liability shall
            not exceed the amount you paid to us in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">9. Intellectual Property</h2>
          <p>
            You retain ownership of your inputs and outputs. We claim no rights over content you generate.
            The Service interface, branding, and proprietary code remain our property.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">10. Privacy</h2>
          <p>
            Your use of the Service is also governed by our{" "}
            <Link href="/privacy" className="text-terminal-400 hover:underline">Privacy Policy</Link>.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">11. Modifications</h2>
          <p>
            We may update these Terms at any time. Material changes will be posted on this page with
            an updated date. Continued use of the Service after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">12. Termination</h2>
          <p>
            You may close your account at any time by contacting us. We may suspend or terminate your
            access for Terms violations. Upon termination, remaining credits are forfeited unless a refund
            is granted under our{" "}
            <Link href="/refund" className="text-terminal-400 hover:underline">Refund Policy</Link>.
          </p>
        </section>

        <section>
          <h2 className="text-neutral-200 text-base font-semibold mb-3">13. Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:support@llm.ai-vfx.com" className="text-terminal-400 hover:underline">
              support@llm.ai-vfx.com
            </a>.
          </p>
        </section>
      </div>

      <div className="mt-16 pt-8 border-t border-surface-300 flex gap-6">
        <Link href="/privacy" className="text-xs font-mono text-surface-800 hover:text-terminal-400 uppercase tracking-widest transition-colors">
          Privacy Policy
        </Link>
        <Link href="/refund" className="text-xs font-mono text-surface-800 hover:text-terminal-400 uppercase tracking-widest transition-colors">
          Refund Policy
        </Link>
      </div>
    </div>
  );
}
